# Generated by Django 5.2.11 on 2026-02-19 11:09

import django.core.validators
import django.db.models.deletion
import django_fsm
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Référence commande')),
                ('adresse_livraison_nom', models.CharField(max_length=150, verbose_name='Nom destinataire')),
                ('adresse_livraison_telephone', models.CharField(max_length=20, verbose_name='Téléphone livraison')),
                ('adresse_livraison_adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('adresse_livraison_ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('adresse_livraison_region', models.CharField(max_length=100, verbose_name='Région')),
                ('adresse_livraison_pays', models.CharField(default='Cameroun', max_length=100, verbose_name='Pays')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant total (FCFA)')),
                ('statut', django_fsm.FSMField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('en_preparation', 'En préparation'), ('expediee', 'Expédiée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=50, protected=True, verbose_name='Statut')),
                ('note_client', models.TextField(blank=True, verbose_name='Note / Instructions de livraison')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de commande')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('date_livraison', models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit_nom', models.CharField(max_length=255, verbose_name='Nom du produit (au moment de la commande)')),
                ('quantite', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prix unitaire (FCFA)')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='orders.commande', verbose_name='Commande')),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_commande', to='products.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('livraison', 'Paiement à la livraison'), ('orange_money', 'Orange Money'), ('mtn_momo', 'MTN Mobile Money'), ('carte', 'Carte bancaire')], default='livraison', max_length=20, verbose_name='Mode de paiement')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('reussi', 'Réussi'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='en_attente', max_length=15, verbose_name='Statut du paiement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant (FCFA)')),
                ('reference_externe', models.CharField(blank=True, max_length=100, verbose_name='Référence externe (transaction)')),
                ('date_paiement', models.DateTimeField(auto_now_add=True, verbose_name='Date du paiement')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='orders.commande', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
    ]
