# Generated by Django 5.2.11 on 2026-03-23 02:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='authorization_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL de paiement NotchPay'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paiement',
            name='telephone_paiement',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numéro Mobile Money'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='date_paiement',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date du paiement confirmé'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='mode',
            field=models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_momo', 'MTN Mobile Money')], max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='reference_externe',
            field=models.CharField(blank=True, max_length=200, verbose_name='Référence NotchPay'),
        ),
    ]
