# Generated by Django 5.2.11 on 2026-02-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=255)),
                ('status_code', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Log Audit',
                'verbose_name_plural': 'Logs Audit',
                'ordering': ['-date'],
            },
        ),
    ]
