# Generated by Django 5.2.11 on 2026-02-19 12:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='La note minimale est 1 étoile.'), django.core.validators.MaxValueValidator(5, message='La note maximale est 5 étoiles.')], verbose_name='Note (1 à 5)')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('is_validated', models.BooleanField(default=False, verbose_name='Validé par un admin')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'avis")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='products.produit', verbose_name='Produit')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avis', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-date_creation'],
                'unique_together': {('utilisateur', 'produit')},
            },
        ),
    ]
