name: CI/CD — Hooyia Market

# ══════════════════════════════════════════════════════════════
# DÉCLENCHEUR
# Ce pipeline se lance automatiquement à chaque push sur "main"
# ══════════════════════════════════════════════════════════════
on:
  push:
    branches: [main]

# Annulation des executions precedentes sur la meme branche pour éviter les redondances
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  # ════════════════════════════════════════════════════════════
  # JOB 1 — TESTS (CI)
  # Lance les tests Django dans un environnement propre
  # ════════════════════════════════════════════════════════════
  tests:
    name: Tests Django
    runs-on: ubuntu-latest

    # Services pour les tests (PostgreSQL + Redis)
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: hooyia_test
          POSTGRES_USER: hooyia
          POSTGRES_PASSWORD: hooyia_test_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

      # redis:
      #   image: redis:7-alpine
      #   ports:
      #     - 6379:6379
      #   options: >-
      #     --health-cmd "redis-cli ping"
      #     --health-interval 5s
      #     --health-timeout 5s
      #     --health-retries 5

    # Variables d'environnement pour les tests
    env:
      SECRET_KEY: "test-secret-key-not-used-in-production"
      DEBUG: "True"
      DB_NAME: hooyia_test
      DB_USER: hooyia
      DB_PASSWORD: hooyia_test_password
      DB_HOST: localhost
      DB_PORT: 5432
      # REDIS_URL: redis://localhost:6379/0
      EMAIL_BACKEND: django.core.mail.backends.locmem.EmailBackend

    steps:
      # 1. Récupère le code source
      - name: Checkout du code
        uses: actions/checkout@v4

      # 2. Installe Python
      - name: Installation de Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      # 3. Installe les dépendances
      - name: installation des dependances
        run: |
          python -m pip install --upgrade pip
          python -m pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: attendre que postgres soit pret
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "Attente de PostgreSQL..."
            sleep 5
          done

      # - name: attendre que redis soit pret
      #   run: |
      #     until redis-cli -h localhost -p 6379 ping | grep PONG; do
      #       echo "Attente de Redis..."
      #       sleep 5
      #     done

      - name: 🛠️ Préparation de la base de données
        run: |
          source venv/bin/activate
          python manage.py migrate --noinput // Applique les migrations sans interaction
          python manage.py collectstatic --noinput -v 0  // Collecte les fichiers statiques sans interaction et sans verbosité

      # 5. Lance les tests Django
      - name: 🧪 Lancement des tests
        run: |
          source venv/bin/activate
          python manage.py test --verbosity=2 | tee test_output.log // Affiche les résultats des tests et les enregistre dans un fichier

      #6. Affiche les resultats des tests en cas d'echecs
      - name: Affichage des resultats des tests
        if: failure ()
        run: |
          echo "❌ Certains tests ont échoué. Voici les détails :"
          cat test_output.log
          exit 1

      - name : envoi notification en cas de succes
        if : success ()
        run: |
          echo "✅ Tous les tests ont réussi ! Prêt pour le déploiement."

      - name: Envoi des emails en cas d'echec
        if: failure ()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME}}
          password: ${{ secrets.EMAIL_PASSWORD}}
          subject: "❌ Échec des tests sur Hooyia Market"
          to: "monthejunior45@gmail.com"
          from: "CI/CD Hooyia MArket"
          body: |
            Bonjour,

            Les tests automatisés pour le projet Hooyia Market ont échoué. Veuillez consulter les logs pour plus de détails.

            Cordialement,
            Votre equipe Hooyia Market
          attachments: test_output.log

  # ════════════════════════════════════════════════════════════
  # JOB 2 — DÉPLOIEMENT (CD)
  # Se connecte au VPS Linode et met à jour l'application
  # Ne se lance QUE si les tests passent ET sur la branche main
  # ════════════════════════════════════════════════════════════
  deploy:
    needs: tests  # Attend que les tests réussissent
    name: Déploiement sur Linode
    runs-on: ubuntu-latest

    steps:
      - name: checkout du code
        uses: actions/checkout@v4

      - name : configuration du SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts // Ajoute le VPS à la liste des hôtes connus pour éviter les prompts de confirmation

      - name: configuration du Username
        run: |
          echo "VPS_USER=${{ secrets.VPS_USER }}" >> $GITHUB_ENV
          echo "VPS_HOST=${{ secrets.VPS_HOST }}" >> $GITHUB_ENV
          echo "VPS_PROJECT_PATH=${{ secrets.VPS_PROJECT_PATH }}" >> $GITHUB_ENV

      - name: deploiement
        run: |
          echo "🚀 Déploiement en cours sur le VPS..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            set -e

            echo "📁 Accès au dossier du projet..."
            cd ${{ secrets.VPS_PROJECT_PATH }}

            echo "⬇️  Récupération du dernier code..."
            git pull origin main

            echo "🐳 Rebuild et redémarrage des conteneurs..."
            docker compose -f docker-compose.prod.yml up -d --build

            echo "🧹 Nettoyage des images Docker inutilisées..."
            docker image prune -f

            echo "✅ Déploiement terminé !"
          EOF // Exécute les commandes de déploiement sur le VPS via SSH

      - name: detail de deploiement
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: notification email en cas d'echec du deploiement
        if: failure ()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME}}
          password: ${{ secrets.EMAIL_PASSWORD}}
          subject: "❌ Échec du déploiement sur Hooyia Market"
          to: "monthejunior45@gmail.com"
          from: "CI/CD Hooyia MArket"
          body: |
            Bonjour,

            Le déploiement de la dernière version de Hooyia Market sur le VPS a échoué. Veuillez vérifier les logs du pipeline pour plus de détails.

            Cordialement,
            Votre Equipe Hooyia Market

      - name: notification email en cas de succes du deploiement
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME}}
          password: ${{ secrets.EMAIL_PASSWORD}}
          subject: "✅ Déploiement réussi sur Hooyia Market"
          to: "monthejunior45@gmail.com"
          from: "CI/CD Hooyia MArket"
          body: |
            Bonjour,

            Le deploiement de la dernière version de Hooyia Market sur le VPS a été effectué avec succès. La nouvelle version est maintenant en ligne !

            Cordialement,
            Votre Equipe Hooyia Market
