# Generated by Django 5.2.11 on 2026-02-19 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('participant1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations_participant1', to=settings.AUTH_USER_MODEL, verbose_name='Participant 1')),
                ('participant2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations_participant2', to=settings.AUTH_USER_MODEL, verbose_name='Participant 2')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-date_creation'],
                'unique_together': {('participant1', 'participant2')},
            },
        ),
        migrations.CreateModel(
            name='MessageChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name='Envoyé le')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation', verbose_name='Conversation')),
                ('expediteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['date_envoi'],
            },
        ),
    ]
